# Generated by Django 2.0.3 on 2018-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='etc',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
