# Generated by Django 2.0.6 on 2018-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_phone_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.CharField(max_length=32),
        ),
    ]
